spring.application.name=botReport
spring.datasource.url=ENC(PI1yoTpI6/v5lvMZ6JRFwvGy6JrA3AxLkiDfYkokUAJQrNK/sZrRXefUiXRH9KhOD43HE2cjTwzW+xX6RqWHUKVNtXm7FIhFwlSLw9tDqENaXmtjApEGzawE19mxkRVOUWxaUlHQ3d6II7/FWBJvJQ==)
spring.datasource.username=ENC(B5h30sMFEnWO3Z2kxjAecg==)
spring.datasource.password=ENC(ykpxe+CMQKBLBRBPVTBw+vRKLCM7ivhM)

jasypt.encryptor.algorithm=PBEWithMD5AndDES
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator
jasypt.encryptor.password=enc@bdat

server.port = 9080


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=freestan17@gmail.com
spring.mail.password=vwjnmajlnzhiabqt
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#logging.level.org.springframework.jdbc.core=DEBUG
#logging.level.org.springframework.jdbc=DEBUG
